/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { NativeModules, FlatList, Platform, StyleSheet, Text, View, Image, TouchableHighlight } from 'react-native';
import { NativoAd } from 'react-native-nativo-ads';
import NativeAdTemplate from "./adTemplates/NativeAdTemplate";
import VideoAdTemplate from "./adTemplates/NativeVideoAdTemplate";
import StandardDisplayAdTemplate from "./adTemplates/StandardDisplayAdTemplate";
import LandingPageTemplate from "./adTemplates/LandingPageAdTemplate";

export default class App extends Component {

  constructor(props) {
    super(props);
    let data = [
      { key: 'Matt' },
      { key: 'Dan' },
      { key: 'Nativo1' },
      { key: 'Dominic' },
      { key: 'Jackson' },
      { key: 'Nativo2' },
      { key: 'James' },
      { key: 'Joel' },
      { key: 'John' },
      { key: 'Nativo3' },
      { key: 'Jillian' },
      { key: 'Greg' },
      { key: 'Julie' },
    ];
    this.state = { data : data };
  }

  render() {
    // Init NativoSDK
    let NativoSDK = NativeModules.NativoSDK;

    NativoSDK.enableDevLogs();
    //NativoSDK.enableTestAdvertisementsWithType(NativoSDK.AdTypes.NO_FILL);
    NativoSDK.enableTestAdvertisements();
    //NativoSDK.prefetchAdForSection("pub.com", "7");

    let itemRender = (props) => {
      console.log("Rendering item: "+JSON.stringify(props));
      //let isNativoAd = props.index === 2 || props.index === 5 || props.index === 8;
      let isNativoAd = props.item.key.indexOf("Nativo") >= 0;
      let NativoAdUnit;

      if (isNativoAd) {
        let showLandingPage = (event) => {
          console.log("LandingPage Event: "+JSON.stringify(event));
          this.props.navigation.navigate('LandingPage', { 
            isNativoAd: true, 
            title: event.title, 
            authorName: event.authorName, 
            authorImgUrl: event.authorImgUrl,
            sectionUrl: event.sectionUrl, 
            index: event.index 
          });
        };
        let showClickoutPage = (event) => {
          this.props.navigation.navigate('ClickoutPage', { articleUrl: event.url });
        };
        let removeNativoAd = (event) => {
          console.log("Remove me: " + event.index + " "+ event.sectionUrl);
          let filteredData = this.state.data;
          filteredData.splice(event.index, 1);
          this.setState({ data : filteredData });
        }
        removeNativoAd = removeNativoAd.bind(this);

        NativoAdUnit = (<NativoAd sectionUrl={"pub.com"} 
                                  index={props.index} 
                                  nativeAdTemplate={{"NativeTemplate" : NativeAdTemplate }}
                                  videoAdTemplate={{"VideoTemplate" : VideoAdTemplate }}
                                  standardDisplayAdTemplate={{"StdTemplate" : StandardDisplayAdTemplate }}
                                  onNativeAdClick={showLandingPage}
                                  onDisplayAdClick={showClickoutPage}
                                  onNeedsRemoveAd={removeNativoAd}
                                  style={{ width: "100%" }} />);
      }
      
      let onArticleClick = () => { 
        let params = { title: "News Article", 
                  authorName: props.item.key, 
                  articleUrl: "https://www.cnn.com/travel/article/which-airline-survey-scli-intl/index.html"};
        this.props.navigation.navigate('LandingPage', params);
      }
      let ArticleUnit = (<View>
                  <Text style={styles.title}>
                    News Article
                  </Text>
                  <View style={styles.authorView}>
                    <Image source={{ uri: "https://www.logolynx.com/images/logolynx/6a/6aa959dca0e6c62f593e94e02332a67f.jpeg" }}
                      style={styles.authorImage} />
                    <Text>By {props.item.key}</Text>
                  </View>
                  <Image source={{ uri: "https://images.unsplash.com/photo-1527664557558-a2b352fcf203?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4341976025ae49162643ccdb47a72a4d&w=300&q=80" }}
                    style={styles.articleImage} />
                </View>);

      return (
        <View style={styles.item}>
            { isNativoAd ? NativoAdUnit : ArticleUnit }
        </View>
      );
    }
  

    return(
        <View style = { styles.container } >
          <Text style={styles.welcome}>☆NativoAds example☆</Text>
          <FlatList data={this.state.data} renderItem={itemRender} style={styles.list} />
        </View>
      );

  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#c9c9c9',
  },
  list: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
    flex: 1
  },
  instructions: {
    color: '#333333',
    marginBottom: 5,
  },
  item: {
    padding: 10,
    backgroundColor: "white",
    margin: 10
  },
  title: {
    alignContent: 'center',
    textAlign: 'center',
    fontSize: 20,
    marginBottom: 5
  },
  authorView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center'
  },
  articleImage: {
    width: "100%",
    height: 110
  },
  authorImage: {
    width: 50,
    height: 20,
    marginBottom: 10,
    marginRight: 10
  }
});
